import Foundation

enum L10n {
    static func text(_ key: String, _ language: AppLanguage) -> String {
        strings[language]?[key] ?? strings[.dutch]?[key] ?? key
    }

    private static let strings: [AppLanguage: [String: String]] = [
        .dutch: [
            "overview": "Overzicht",
            "tickets": "Loten",
            "chance": "Kans",
            "bonus": "Bonus",
            "profile": "Profiel",
            "settings": "Instellingen",
            "my_tickets": "Mijn Loten",
            "win_chances": "Winkansen",
            "calendar": "Kalender",
            "bonuses": "Bonussen",
            "hi": "Hoi",
            "welcome_today": "Veel speelplezier vandaag",
            "responsible_play": "Speel bewust",
            "responsible_notice": "De kansberekening toont statistische trends en is geen garantie. Elke trekking is onafhankelijk.",
            "language": "Taal",
            "guest_account": "Gastaccount",
            "signed_in": "Ingelogd",
            "sign_in": "Inloggen",
            "notifications": "Meldingen",
            "draw_reminder": "Herinnering 24 uur voor trekking",
            "notification_note": "Deze versie bewaart alleen je voorkeur. Er worden geen pushmeldingen gepland.",
            "responsible_section": "Verantwoord spelen",
            "monthly_limit": "Maandlimiet",
            "help_advice": "Hulp en advies",
            "security": "Veiligheid",
            "change_password": "Wachtwoord wijzigen",
            "close": "Sluiten",
            "done": "Gereed",
            "username": "Gebruikersnaam",
            "password": "Wachtwoord",
            "invalid_login": "Deze gegevens zijn niet geldig. Controleer je gebruikersnaam en wachtwoord.",
            "current_password": "Huidig wachtwoord",
            "new_password": "Nieuw wachtwoord",
            "change_password_action": "Wijzig wachtwoord",
            "password_unavailable": "Wachtwoord wijzigen is alleen beschikbaar na echte accountkoppeling.",
            "previous_month": "Vorige maand",
            "next_month": "Volgende maand",
            "amount": "Bedrag",
            "cancel": "Annuleer",
            "save": "Bewaar",
            "future_draw": "Blauw: toekomstige trekking op de 10e",
            "past_draw": "Groen: afgelopen trekking met eigen jackpotbedrag",
            "calendar_hint": "Tik op de 10e van een maand om een jackpotbedrag vast te leggen.",
            "drawing_on": "Trekking op",
            "jackpot_for": "Jackpot voor"
            ,
            "no_tickets": "Geen loten",
            "no_tickets_message": "Voeg handmatig een lot toe of probeer een scan.",
            "add_ticket": "Lot toevoegen",
            "scan_ticket": "Lot scannen",
            "camera": "Camera",
            "gallery": "Galerij",
            "delete": "Verwijder",
            "delete_ticket": "Verwijder lot",
            "delete_ticket_question": "Dit lot verwijderen?",
            "manual_add": "Handmatig toevoegen",
            "ticket_not_recognized": "Lot niet herkend",
            "ticket_not_recognized_message": "De afbeelding kon niet betrouwbaar worden gelezen. Voeg het lot handmatig toe.",
            "ticket_details": "Lotdetails",
            "ticket": "Lot",
            "number": "Nummer",
            "series": "Serie",
            "draw": "Trekking",
            "status": "Status",
            "prize_amount": "Prijsbedrag",
            "note": "Notitie",
            "save_changes": "Bewaar wijzigingen",
            "new_ticket": "Nieuw lot",
            "ticket_number": "Lotnummer",
            "valid_ticket_number": "Vul een geldig lotnummer in.",
            "valid_series": "Vul een geldige serie in.",
            "calculate_chance": "Winkans berekenen",
            "draw_type": "Type trekking",
            "statistics_period": "Statistiekperiode",
            "calculate": "Bereken kans",
            "no_calculation": "Nog geen berekening",
            "no_calculation_message": "Vul je lotnummer en serie in om een kansrapport te maken.",
            "probability_analysis": "Kansanalyse",
            "prize_ranges": "Prijsbereiken",
            "expected_value": "Verwachte waarde",
            "export_pdf": "Exporteer als PDF",
            "share_pdf": "Deel PDF-rapport",
            "export_failed": "Export mislukt",
            "export_failed_message": "Het PDF-rapport kon niet worden gemaakt.",
            "calculating": "Statistische patronen worden bekeken...",
            "bonus_activated": "Bonus geactiveerd",
            "bonus_linked": "is gekoppeld aan je QR-code.",
            "available_bonuses": "Beschikbare bonussen",
            "active_count": "6 actief",
            "activate": "Activeer"
            ,
            "activated": "Geactiveerd"
        ],
        .english: [
            "overview": "Overview",
            "tickets": "Tickets",
            "chance": "Chance",
            "bonus": "Bonus",
            "profile": "Profile",
            "settings": "Settings",
            "my_tickets": "My Tickets",
            "win_chances": "Win Chances",
            "calendar": "Calendar",
            "bonuses": "Bonuses",
            "hi": "Hi",
            "welcome_today": "Enjoy playing today",
            "responsible_play": "Play responsibly",
            "responsible_notice": "The probability calculation shows statistical trends and is not a guarantee. Every draw is independent.",
            "language": "Language",
            "guest_account": "Guest account",
            "signed_in": "Signed in",
            "sign_in": "Sign In",
            "notifications": "Notifications",
            "draw_reminder": "Reminder 24 hours before draw",
            "notification_note": "This version only saves your preference. No push notifications are scheduled.",
            "responsible_section": "Responsible play",
            "monthly_limit": "Monthly limit",
            "help_advice": "Help and advice",
            "security": "Security",
            "change_password": "Change password",
            "close": "Close",
            "done": "Done",
            "username": "Username",
            "password": "Password",
            "invalid_login": "These credentials are not valid. Check your username and password.",
            "current_password": "Current password",
            "new_password": "New password",
            "change_password_action": "Change password",
            "password_unavailable": "Changing password is only available after connecting a real account.",
            "previous_month": "Previous month",
            "next_month": "Next month",
            "amount": "Amount",
            "cancel": "Cancel",
            "save": "Save",
            "future_draw": "Blue: upcoming draw on the 10th",
            "past_draw": "Green: past draw with your jackpot amount",
            "calendar_hint": "Tap the 10th of a month to record a jackpot amount.",
            "drawing_on": "Draw on",
            "jackpot_for": "Jackpot for",
            "no_tickets": "No tickets",
            "no_tickets_message": "Add a ticket manually or try scanning.",
            "add_ticket": "Add ticket",
            "scan_ticket": "Scan ticket",
            "camera": "Camera",
            "gallery": "Gallery",
            "delete": "Delete",
            "delete_ticket": "Delete ticket",
            "delete_ticket_question": "Delete this ticket?",
            "manual_add": "Add manually",
            "ticket_not_recognized": "Ticket not recognized",
            "ticket_not_recognized_message": "The image could not be read reliably. Add the ticket manually.",
            "ticket_details": "Ticket details",
            "ticket": "Ticket",
            "number": "Number",
            "series": "Series",
            "draw": "Draw",
            "status": "Status",
            "prize_amount": "Prize amount",
            "note": "Note",
            "save_changes": "Save changes",
            "new_ticket": "New ticket",
            "ticket_number": "Ticket number",
            "valid_ticket_number": "Enter a valid ticket number.",
            "valid_series": "Enter a valid series.",
            "calculate_chance": "Calculate win chance",
            "draw_type": "Draw type",
            "statistics_period": "Statistics period",
            "calculate": "Calculate chance",
            "no_calculation": "No calculation yet",
            "no_calculation_message": "Enter your ticket number and series to create a chance report.",
            "probability_analysis": "Chance analysis",
            "prize_ranges": "Prize ranges",
            "expected_value": "Expected value",
            "export_pdf": "Export as PDF",
            "share_pdf": "Share PDF report",
            "export_failed": "Export failed",
            "export_failed_message": "The PDF report could not be created.",
            "calculating": "Checking statistical patterns...",
            "bonus_activated": "Bonus activated",
            "bonus_linked": "is linked to your QR code.",
            "available_bonuses": "Available bonuses",
            "active_count": "6 active",
            "activate": "Activate",
            "activated": "Activated"
        ]
    ]
}

extension AppStore {
    var language: AppLanguage {
        data.settings.language
    }

    func t(_ key: String) -> String {
        L10n.text(key, language)
    }
}
